version: '3.9'

services:
  postgresql:
    container_name: postgresql
    image: postgres:15.0-alpine
    hostname: postgresql.local
    environment:
      POSTGRES_DB: tenis-db
      POSTGRES_USER: tenis-user
      POSTGRES_PASSWORD: tenis-password
    expose:
      - 5432
    volumes:
      - postgres_torneios_data:/var/lib/postgresql/data
    networks:
      tenis-network:
        ipv4_address: 10.211.55.1
  backend:
    container_name: backend
    hostname: tenis-backend.local
    image: tenis-backend:latest
    environment:
      DATABASE_URL: postgresql://tenis-user:tenis-password@postgresql.local:5432/tenis-db?schema=public
    depends_on:
      - postgresql
    expose:
      - 3333
    networks:
      tenis-network:
        ipv4_address: 10.211.55.2
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx.local
    expose:
      - 80
      - 443
    depends_on:
      - backend
    external_links:
      - '192.168.100.43:3333:192.168.100.43:3333'
    networks:
      tenis-network:
        ipv4_address: 10.211.55.6
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx-ssl:/ssl
      - ./docker/nginx-www:/www/site

volumes:
  postgres_torneios_data:
networks:
  tenis-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.211.55.0/16
